"""fix order table 

Revision ID: 55e4396ef8ca
Revises: bcc5aa669897
Create Date: 2025-06-23 17:03:01.944613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '55e4396ef8ca'
down_revision: Union[str, None] = 'bcc5aa669897'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Convert pickup_location to JSONB using explicit casting
    op.execute("""
        ALTER TABLE orders
        ALTER COLUMN pickup_location
        TYPE JSONB
        USING pickup_location::jsonb
    """)

    # Convert delivery_location to JSONB using explicit casting
    op.execute("""
        ALTER TABLE orders
        ALTER COLUMN delivery_location
        TYPE JSONB
        USING delivery_location::jsonb
    """)



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'delivery_location',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('orders', 'pickup_location',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
