"""refactor order model and add payment model

Revision ID: d7289e4b3ff9
Revises: db0fdd30f97a
Create Date: 2025-06-25 03:00:02.434909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7289e4b3ff9'
down_revision: Union[str, None] = 'db0fdd30f97a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reference', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_up', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_index(op.f('ix_payments_reference'), 'payments', ['reference'], unique=True)
    op.drop_constraint(op.f('order_status_history_order_id_fkey'), 'order_status_history', type_='foreignkey')
    op.create_foreign_key(None, 'order_status_history', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.add_column('orders', sa.Column('payment_id', sa.UUID(), nullable=True))
    op.add_column('orders', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'orders', 'payments', ['payment_id'], ['id'])
    op.drop_constraint(op.f('proof_of_delivery_order_id_fkey'), 'proof_of_delivery', type_='foreignkey')
    op.create_foreign_key(None, 'proof_of_delivery', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'proof_of_delivery', type_='foreignkey')
    op.create_foreign_key(op.f('proof_of_delivery_order_id_fkey'), 'proof_of_delivery', 'orders', ['order_id'], ['id'])
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'is_verified')
    op.drop_column('orders', 'payment_id')
    op.drop_constraint(None, 'order_status_history', type_='foreignkey')
    op.create_foreign_key(op.f('order_status_history_order_id_fkey'), 'order_status_history', 'orders', ['order_id'], ['id'])
    op.drop_index(op.f('ix_payments_reference'), table_name='payments')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_table('payments')
    # ### end Alembic commands ###
