"""make driver_id null to be true

Revision ID: db0fdd30f97a
Revises: 55e4396ef8ca
Create Date: 2025-06-23 21:05:43.657905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db0fdd30f97a'
down_revision: Union[str, None] = '55e4396ef8ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'driver_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'driver_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
